<section>
    <p class="text-right"><a href="listecommentaires.php" class="btn btn-primary"><i class="icon-plus-square"></i> Ajouter un commentaire</a></p>
    <table id="tableDonnee" class="table">
        <thead>
            <th>Pseudo</th>
            <th>Commentaire</th>
            <th></th>
        </thead>
        <tbody>
            <?php foreach ($comments as $comment) : ?>
                <tr>
                    <td><?= $comment['com_pseudo'] ?></td>
                    <td><?= $comment['com_content'] ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>