<div class="container">
    <form method="post" action="register.php" class="login-form d-flex flex-column justify-content-center">
        <div class="form-group">
            <label for="mail">Adresse Mail</label>
            <input type="email" name="email" class="form-control" id="mail" aria-describedby="emailHelp" placeHolder="Entrez votre adresse email." />
            <small id="emailHelp" class="form-text text-muted">Vous pemettra de vous connecter (sans dec).</small>
        </div>
        <div class="form-group">
            <label for="pwd">Mot de Passe</label>
            <input type="password" name="passwd" class="form-control" id="pwd" placeHolder="Entrez votre mot de passe." />
            <small class="form-text text-muted">Doit contenir au moins une majuscule, un caractère spécial et un chiffre.</small>
        </div>
        <div class="form-group">
            <label for="pwd_rpt">Confirmez Mot de Passe</label>
            <input type="password" name="passwd_repeat" class="form-control" id="pwd_rpt" placeHolder="Répétez votre mot de passe." />
        </div>
        <button type="submit" name="register" class="btn btn-primary btn-block btn-form">Créer</button>
    </form>
</div>