<div class="container">
    <!--SLIDE1-->
    <div class="slide" id="slide1" data-slide="1" data-stellar-background-ratio="0.5">

        <div class="wrapper">

            <img src="img/slide1/neurone1.png" data-stellar-ratio="2.4" data-stellar-vertical-offset="-102" alt="schéma d'une neuronne">
            <img src="img/slide1/neurone2.png" data-stellar-ratio="1" data-stellar-vertical-offset="-53" alt="schéma d'une neuronne">
            <img src="img/slide1/neurone3.png" data-stellar-ratio="2.5" data-stellar-vertical-offset="-250" alt="schéma d'une neuronne">
            <img src="img/slide1/neurone2.png" data-stellar-ratio="1" data-stellar-vertical-offset="-93" alt="schéma d'une neuronne">
            <img src="img/slide1/neurone3.png" data-stellar-ratio="1.5" data-stellar-vertical-offset="-450" alt="schéma d'une neuronne">
            <img src="img/slide1/neurone1.png" data-stellar-ratio="0.8" data-stellar-vertical-offset="-100" alt="schéma d'une neuronne">

        </div>

        <span class="parallax1">Les biomédicaments</span>



        <p class="article-biotech1">
            Du vivant pour soigner les êtres vivants… Tel pourrait être résumé le principe des biomédicaments. Ces
            traitements font progresser la médecine depuis plusieurs années. Ils sont produits à partir de cellules
            biologiques, cultivées en laboratoire pour obtenir des anticorps, et agissent ainsi sur des molécules de
            notre
            propre organisme.

            Grâce à leur action plus ciblée que la chimie traditionnelle, ils soignent plus efficacement, avec moins
            d’effets secondaires. Les biomédicaments apportent un réel espoir pour les patients atteints de maladies
            complexes ou rares. <i><a href="https://www.novartis.fr/notre-travail/notre-rd/les-biomedicaments">En savoir
                    plus</a> </i>
        </p>
        <span class="slideno">BIOTECHNOLOGIE</span>

        <a class="button" data-slide="2" title=""></a>

    </div>



    <!--Slide 2-->

    <div class="slide" id="slide2" data-slide="2" data-stellar-background-ratio="0">


        <span class="parallax2">Des neurones artificiels pour restaurer les fonctions du corps</span>
        <p class="article-biotech2">
            Des chercheurs de l'université de Bath sont parvenus à développer des neurones artificiels reproduisant le
            comportement de neurones biologiques. Une technologie qui pourrait avoir de nombreuses applications pour,
            par exemple, compenser des insuffisances cardiaques ou des maladies dégénératives. Voire servir de base aux
            interfaces humain-machines de demain. Rien à voir avec l’intelligence artificielle mais nous sommes en plein
            dans l'homme augmenté. Cette fois-ci, le terme “neurone artificiel” doit être entendu au sens littéral. Des
            neurones sur puce de silicium capables de fonctionner comme leurs homologues biologiques et de faire passer
            des messages électriques dans le corps. A terme, ces puces pourraient être intégrées à des dispositifs
            médicaux pour remplacer les neurones biologiques défaillants ou abîmés, par exemple pour prévenir les
            insuffisances cardiaques. <i><a href="https://www.usinenouvelle.com/editorial/des-neurones-artificiels-pour-restaurer-les-fonctions-du-corps.N910844">En
                    savoir plus</a> </i>

        </p>
        <span class="slideno">BIOTECHNOLOGIE</span>
    </div>



    <!--Slide 3 sante-->

    <div class="slide" id="slide3" data-slide="3" data-stellar-background-ratio="0.5">

        <div class="wrapper">

            <img src="img/slide3/adn.jpg" data-stellar-ratio="2.4" data-stellar-vertical-offset="-102" alt="image représentant de l'adn">
            <img src="img/slide3/montre.jpg" data-stellar-ratio="1" data-stellar-vertical-offset="-53" alt="image d'une montre connectée qui effectue un ECG">
            <img src="img/slide3/ia.jpg" data-stellar-ratio="2.5" data-stellar-vertical-offset="-50" alt="image représentant deux visages connectés">
            <img src="img/slide3/imp.jpg" data-stellar-ratio="0.8" data-stellar-vertical-offset="-180" alt="image représentant une imprimante3D">
            <img src="img/slide3/pc.jpg" data-stellar-ratio="1.2" data-stellar-vertical-offset="-230" alt="image représentant les trois pc">

        </div>

        <span class="parallax3">Biotechnologies et traitements des troubles oculaires !</span>
        <p class="article-biotech3">
            Nombreux sont les troubles de la vue liés ou pas à l’âge mais dans tous les cas, traiter les troubles
            oculaires fait naître beaucoup d’espoirs, avec les technologies mises au point, permettant aux patients de
            faire face, selon la maladie. Des recherches ont permis à des blocs opératoires de disposer d’appareils de
            pointe permettant à ceux qui souffrent de la cataracte de subir avec une grande précision la chirurgie
            adéquate. Il arrive que certaines personnes atteintes de la presbytie se font implanter des lentilles
            intraoculaires pour corriger leur vue, tandis que d’autres expérimentations sont en cours pour solutionner
            les problèmes de Dégénérescence maculaire liée à l’âge ou DMLA. Parmi ces études, le principe d’implantation
            de cellules souches est en phase d’essai. <i><a href=" http://www.defi-biotech-sante.org/biotechnologies-et-traitements-des-troubles-oculaires/">En
                    savoir plus</a></i>
        </p>

        <span class="slideno">BIOTECHNOLOGIE</span>
        <a class="button" data-slide="4" title=""></a>

    </div>

    <!--SLIDE 4 contact-->

    <div class="slide" id="slide4" data-slide="4" data-stellar-background-ratio="0">

        <span class="parallax4">Séquençage de l'ADN</span>

        <p class="article-biotech4">
            Quinze ans après le décryptage du premier génome humain, le séquençage de l'ADN s'impose à l'hôpital, pour
            offrir à des centaines de milliers de patients diagnostic plus rapide et traitement sur mesure. Une vraie
            révolution médicale, que décrypte Elsa Abdoun. En avril 2003, la nouvelle fait la une de tous les journaux :
            pour la première fois, un génome humain complet a été séquencé. Un véritable exploit, qui a nécessité plus
            d'une décennie de travail et coûté 2,7 milliards de dollars. Douze ans plus tard, décrypter des fragments
            d'ADN est devenu un examen médical comme un autre... <i><a href="
                    https://www.science-et-vie.com/corps-et-sante/sequencage-de-l-adn-il-sauve-desormais-des-vies-33258">En savoir plus</a>
            </i>
        </p>
        <span class="slideno">BIOTECHNOLOGIE</span>



    </div>
    </container>